project:
  type: website
  output-dir: docs

website:
  title:  "Brett Devine is the best"
  favicon: /img/bd_square_logo-48.ico
  navbar:
    title: false
    logo: /img/bd_logo_border.png
    left: # aligns navbar items to the right/left/center
      - text: Posts
        icon: clipboard-data
        href: posts/index.qmd
      - text: Projects
        href: projects/index.qmd
        icon: code-square
      - text: Teaching
        href: teaching/index.qmd
        icon: book-half
      - text: CV
        href: cv/index.qmd
        icon: file-person
    page-footer:
      background: light
      right: 
        - icon: github
          href: https://github.com/brettdevine
        - icon: linkedin
          href: https://www.linkedin.com/in/brett-devine/

format:
  html:
    theme:
      - styles.scss
    mainfont: Lato
    toc: true



