project:
  type: website
  output-dir: docs

website:
  title:  "Brett Devine"
  navbar:
    title: false
    right: # aligns navbar items to the right/left/center
      - text: Posts
        href: posts/index.qmd
      - text: CV
        href: cv/index.qmd
    page-footer:
      background: light
      right: 
        - icon: github
          href: https://github.com/brettdevine
        - icon: linkedin
          href: https://www.linkedin.com/in/brett-devine/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



