project:
  type: website

website:
  title:  "![](bd_logo.png){width=0.5in}"
  navbar:
    background: primary
    search: true
    right:
      - href: index.qmd
        text: Home
      - projects.qmd
      - CV.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



